name       : libnest2d
version    : 0.4
release    : 1
source     :
    - git|https://github.com/tamasmeszaros/libnest2d : da4782500da4eb8cb6e38e5e3f10164ec5a59778
license    : LGPL-3.0-or-later
component  : programming.devel
summary    : Library for the 2D bin packaging problem
description: |
    2D irregular bin packaging and nesting library written in modern C++.
patterns   : /usr
builddeps  :
    - pkgconfig(nlopt)
    - pkgconfig(polyclipping)
    - libboost-devel
rundeps    :
    - libboost-devel
    - nlopt-devel
    - polyclipping-devel
setup      : |
    # https://github.com/tamasmeszaros/libnest2d/pull/18
    %patch -p1 < $pkgfiles/18.patch

    %cmake_ninja -DLIBNEST2D_HEADER_ONLY=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
